openapi: 3.0.0
info:
    title: User Information API
    description: API to retrieve user's personal information.
    version: "1.0.0"
servers:
    - url: https://apparel-search-prod-2-kvkd25vxnq-uc.a.run.app
paths:
    /get_user_info:
        get:
            summary: Retrieve user's personal information
            operationId: getUserInfo
            requestBody:
                description: empty string
                content:
                    application/json:
                        schema:
                            type: string
            responses:
                default:
                    description: User's personal information
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    delivery_address:
                                        type: string
                                    payment_info:
                                        type: string
                                    contact_number:
                                        type: string
                                    email:
                                        type: string
